<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="34929" started-at="2020-02-20T15:05:53Z" finished-at="2020-02-20T15:06:27Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="34929" started-at="2020-02-20T15:05:53Z" finished-at="2020-02-20T15:06:27Z">
      <class name="practise.DynamicTableCases">
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:practise.DynamicTableCases@55f3ddb1]" name="beforeMethod" is-config="true" duration-ms="12940" started-at="2020-02-20T20:35:53Z" finished-at="2020-02-20T20:36:06Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="PASS" signature="GroupAcalculatesumofprevclose()[pri:1, instance:practise.DynamicTableCases@55f3ddb1]" name="GroupAcalculatesumofprevclose" duration-ms="5164" started-at="2020-02-20T20:36:06Z" finished-at="2020-02-20T20:36:11Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- GroupAcalculatesumofprevclose -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:practise.DynamicTableCases@55f3ddb1]" name="afterMethod" is-config="true" duration-ms="1513" started-at="2020-02-20T20:36:11Z" finished-at="2020-02-20T20:36:12Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method status="PASS" signature="beforeMethod()[pri:0, instance:practise.DynamicTableCases@55f3ddb1]" name="beforeMethod" is-config="true" duration-ms="9647" started-at="2020-02-20T20:36:12Z" finished-at="2020-02-20T20:36:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method status="FAIL" signature="verifycompanycurrentprice()[pri:2, instance:practise.DynamicTableCases@55f3ddb1]" name="verifycompanycurrentprice" duration-ms="4155" started-at="2020-02-20T20:36:22Z" finished-at="2020-02-20T20:36:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[NIIT Technologies current month price is less than 500 expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: NIIT Technologies current month price is less than 500 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:93)
	at org.testng.Assert.failNotEquals(Assert.java:512)
	at org.testng.Assert.assertTrue(Assert.java:41)
	at practise.DynamicTableCases.verifycompanycurrentprice(DynamicTableCases.java:114)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:661)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:230)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:76)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifycompanycurrentprice -->
        <test-method status="PASS" signature="afterMethod()[pri:0, instance:practise.DynamicTableCases@55f3ddb1]" name="afterMethod" is-config="true" duration-ms="1470" started-at="2020-02-20T20:36:26Z" finished-at="2020-02-20T20:36:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
      </class> <!-- practise.DynamicTableCases -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
